apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortress-app
  namespace: default
  labels:
    app: fortress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortress-app
  template:
    metadata:
      labels:
        app: fortress-app
    spec:
      # Pod level - not root
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
      containers:
        - name: secure-nginx
          image: ghcr.io/joselorenzana272/fortress-in-a-box:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          # Container level - not root
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            allowPrivilegeEscalation: false