name: Build test

on:
    push:

jobs:
    build-image:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repository
              uses: actions/checkout@v4

            - name: Build the Docker image
              run: docker build -t fortress-in-a-box .

            - name: Run Trivy scanner
              uses: aquasecurity/trivy-action@0.35.0
              with:
                image-ref: fortress-in-a-box
                format: 'table'
                exit-code: '1'
                vuln-type: 'os,library'
                severity: 'CRITICAL,HIGH'
                ignore-unfixed: true